package com.nexorialabpro.shiftplanner;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import android.graphics.drawable.GradientDrawable;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    static final double VAC_HOURS = 6.0;
    static final int REQ_OPEN=10, REQ_SAVE_NSP=11, REQ_SAVE_CSV=12;
    final String[] langs={"Italiano","English","Español","Français","Deutsch"};
    final String[] langCodes={"it","en","es","fr","de"};
    final String[] shiftCodes={"NONE","M","P","N","G","R","F","PERM","MAL","CUSTOM"};
    final String[] otCodes={"OT","ONCALL","EXT","RECALL","OTHER"};
    JSONObject data=new JSONObject(); int year,month,selectedDay=-1; String lang="it";
    LinearLayout root,summary,editor,otPanel; GridLayout calendar; TextView monthTitle; EditText nameEd,deptEd,startEd,endEd,noteEd,onStartEd,onEndEd,otStartEd,otEndEd,otHoursEd,otNoteEd; Spinner langSp,shiftSp,otTypeSp; CheckBox onCheck; TextView otList;
    final int navy=Color.rgb(11,16,38),panel=Color.rgb(21,28,59),panel2=Color.rgb(16,22,47),text=Color.rgb(245,247,255),muted=Color.rgb(170,179,214),blue=Color.rgb(45,124,255),violet=Color.rgb(139,92,246),cyan=Color.rgb(34,211,238);

    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(navy); load(); build(); render();}
    String tr(String k){
        Map<String,String[]> m=new HashMap<>();
        m.put("title",new String[]{"Nexoria ShiftPlanner PRO","Nexoria ShiftPlanner PRO","Nexoria ShiftPlanner PRO","Nexoria ShiftPlanner PRO","Nexoria ShiftPlanner PRO"});
        m.put("name",new String[]{"Nome","Name","Nombre","Nom","Name"}); m.put("dept",new String[]{"Reparto / Ufficio","Department / Office","Departamento / Oficina","Service / Bureau","Abteilung / Büro"});
        m.put("regular",new String[]{"Turno ordinario","Regular shift","Turno ordinario","Service normal","Reguläre Schicht"}); m.put("start",new String[]{"Inizio","Start","Inicio","Début","Beginn"}); m.put("end",new String[]{"Fine","End","Fin","Fin","Ende"});
        m.put("note",new String[]{"Nota","Note","Nota","Note","Notiz"}); m.put("oncall",new String[]{"Reperibile in questo giorno","On call this day","De guardia este día","Astreinte ce jour","Rufbereitschaft an diesem Tag"});
        m.put("apply",new String[]{"Salva giornata","Save day","Guardar día","Enregistrer le jour","Tag speichern"}); m.put("clear",new String[]{"Cancella giornata","Clear day","Borrar día","Effacer le jour","Tag löschen"});
        m.put("overtime",new String[]{"Straordinari / attivazioni","Overtime / activations","Horas extra / activaciones","Heures sup. / activations","Überstunden / Einsätze"});
        m.put("add",new String[]{"Aggiungi straordinario","Add overtime","Añadir horas extra","Ajouter heures sup.","Überstunden hinzufügen"});
        m.put("export",new String[]{"Esporta progetto .nsp","Export .nsp project","Exportar proyecto .nsp","Exporter projet .nsp",".nsp-Projekt exportieren"});
        m.put("import",new String[]{"Apri progetto .nsp","Open .nsp project","Abrir proyecto .nsp","Ouvrir projet .nsp",".nsp-Projekt öffnen"});
        m.put("csv",new String[]{"Esporta CSV","Export CSV","Exportar CSV","Exporter CSV","CSV exportieren"});
        m.put("worked",new String[]{"Giorni lavorati","Days worked","Días trabajados","Jours travaillés","Arbeitstage"}); m.put("hours",new String[]{"Ore ordinarie","Ordinary hours","Horas ordinarias","Heures normales","Regelstunden"});
        m.put("vac",new String[]{"Ore ferie retribuite","Paid vacation hours","Horas vacaciones pagadas","Heures congés payées","Bezahlte Urlaubsstunden"}); m.put("nights",new String[]{"Notti","Nights","Noches","Nuits","Nächte"});
        m.put("onc",new String[]{"Giorni reperibili","On-call days","Días de guardia","Jours d'astreinte","Rufbereitschaftstage"}); m.put("oth",new String[]{"Ore straordinarie","Overtime hours","Horas extra","Heures sup.","Überstunden"});
        int i=Arrays.asList(langCodes).indexOf(lang); if(i<0)i=0; String[] a=m.get(k); return a==null?k:a[i];
    }
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextColor(text);t.setTextSize(sp);t.setPadding(dp(4),dp(4),dp(4),dp(4));return t;}
    GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(40,50,95));return g;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{blue,violet});g.setCornerRadius(dp(14));b.setBackground(g);b.setAllCaps(false);return b;}
    EditText ed(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setTextColor(text);e.setBackground(bg(panel2,12));e.setPadding(dp(12),dp(9),dp(12),dp(9));return e;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(12),dp(10),dp(12),dp(10));l.setBackground(bg(panel,16));return l;}
    void build(){
        ScrollView sc=new ScrollView(this); sc.setFillViewport(true); sc.setBackgroundColor(navy); root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(24));sc.addView(root);setContentView(sc);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL); ImageView logo=new ImageView(this);logo.setImageResource(com.nexorialabpro.shiftplanner.R.mipmap.ic_launcher);head.addView(logo,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);TextView title=tv("Nexoria\nShiftPlanner PRO",22);title.setTypeface(Typeface.DEFAULT_BOLD);ht.addView(title);ht.addView(tv("Android Edition · Turni, reperibilità e straordinari",12));head.addView(ht,new LinearLayout.LayoutParams(0,-2,1));langSp=new Spinner(this);ArrayAdapter<String> la=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,langs);langSp.setAdapter(la);langSp.setSelection(Math.max(0,Arrays.asList(langCodes).indexOf(lang)));head.addView(langSp);root.addView(head);
        langSp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){String n=langCodes[pos];if(!n.equals(lang)){lang=n;save();recreate();}}});
        LinearLayout person=card();person.addView(tv(tr("name"),13));nameEd=ed(tr("name"));nameEd.setText(data.optString("name"));person.addView(nameEd);person.addView(tv(tr("dept"),13));deptEd=ed(tr("dept"));deptEd.setText(data.optString("department"));person.addView(deptEd);root.addView(person,lpTop(10));
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);Button prev=btn("‹");monthTitle=tv("",21);monthTitle.setGravity(Gravity.CENTER);monthTitle.setTypeface(Typeface.DEFAULT_BOLD);Button next=btn("›");nav.addView(prev,new LinearLayout.LayoutParams(dp(56),-2));nav.addView(monthTitle,new LinearLayout.LayoutParams(0,-2,1));nav.addView(next,new LinearLayout.LayoutParams(dp(56),-2));root.addView(nav,lpTop(12));prev.setOnClickListener(v->{month--;if(month<0){month=11;year--;}selectedDay=-1;save();render();});next.setOnClickListener(v->{month++;if(month>11){month=0;year++;}selectedDay=-1;save();render();});
        summary=new LinearLayout(this);summary.setOrientation(LinearLayout.HORIZONTAL);summary.setGravity(Gravity.CENTER_VERTICAL);root.addView(summary,lpTop(8));
        calendar=new GridLayout(this);calendar.setColumnCount(7);calendar.setUseDefaultMargins(false);root.addView(calendar,lpTop(8));
        editor=card();root.addView(editor,lpTop(12));buildEditor(); otPanel=card();root.addView(otPanel,lpTop(12));buildOT();
        LinearLayout files=card();Button open=btn(tr("import")),exp=btn(tr("export")),csv=btn(tr("csv"));files.addView(open);files.addView(exp,lpTop(6));files.addView(csv,lpTop(6));root.addView(files,lpTop(12));open.setOnClickListener(v->openProject());exp.setOnClickListener(v->createDoc(false));csv.setOnClickListener(v->createDoc(true));
    }
    LinearLayout.LayoutParams lpTop(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}
    void buildEditor(){editor.removeAllViews();TextView h=tv(tr("regular"),18);h.setTypeface(Typeface.DEFAULT_BOLD);editor.addView(h);shiftSp=new Spinner(this);shiftSp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,shiftLabels()));editor.addView(shiftSp);LinearLayout times=new LinearLayout(this);startEd=ed(tr("start")+" 07:00");endEd=ed(tr("end")+" 14:42");times.addView(startEd,new LinearLayout.LayoutParams(0,-2,1));times.addView(endEd,new LinearLayout.LayoutParams(0,-2,1));editor.addView(times,lpTop(6));noteEd=ed(tr("note"));noteEd.setMinLines(2);editor.addView(noteEd,lpTop(6));onCheck=new CheckBox(this);onCheck.setText(tr("oncall"));onCheck.setTextColor(text);editor.addView(onCheck,lpTop(6));LinearLayout oc=new LinearLayout(this);onStartEd=ed("14:42");onEndEd=ed("22:00");oc.addView(onStartEd,new LinearLayout.LayoutParams(0,-2,1));oc.addView(onEndEd,new LinearLayout.LayoutParams(0,-2,1));editor.addView(oc);Button apply=btn(tr("apply")),clear=btn(tr("clear"));editor.addView(apply,lpTop(8));editor.addView(clear,lpTop(6));apply.setOnClickListener(v->applyDay());clear.setOnClickListener(v->clearDay());}
    String[] shiftLabels(){return new String[]{"—","M · Mattina / Morning","P · Pomeriggio / Afternoon","N · Notte / Night","G · Giornaliero / Day","R · Riposo / Rest","F · Ferie / Vacation","PERM · Permesso / Leave","MAL · Malattia / Sick","CUSTOM · Personalizzato / Custom"};}
    void buildOT(){otPanel.removeAllViews();TextView h=tv(tr("overtime"),18);h.setTypeface(Typeface.DEFAULT_BOLD);otPanel.addView(h);otTypeSp=new Spinner(this);otTypeSp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Straordinario / Overtime","Attivazione reperibilità / On-call activation","Prolungamento turno / Shift extension","Rientro / Recall","Altro / Other"}));otPanel.addView(otTypeSp);LinearLayout row=new LinearLayout(this);otStartEd=ed("Start");otEndEd=ed("End");otHoursEd=ed("Hours");row.addView(otStartEd,new LinearLayout.LayoutParams(0,-2,1));row.addView(otEndEd,new LinearLayout.LayoutParams(0,-2,1));row.addView(otHoursEd,new LinearLayout.LayoutParams(0,-2,1));otPanel.addView(row,lpTop(6));otNoteEd=ed(tr("note"));otPanel.addView(otNoteEd,lpTop(6));Button add=btn(tr("add"));otPanel.addView(add,lpTop(6));otList=tv("",13);otPanel.addView(otList,lpTop(8));add.setOnClickListener(v->addOT());}
    void render(){monthTitle.setText(new DateFormatSymbols(locale()).getMonths()[month]+" "+year);renderSummary();renderCalendar();loadSelected();renderOT();}
    Locale locale(){switch(lang){case"en":return Locale.ENGLISH;case"es":return new Locale("es");case"fr":return Locale.FRENCH;case"de":return Locale.GERMAN;default:return Locale.ITALIAN;}}
    JSONObject days(){JSONObject d=data.optJSONObject("days");if(d==null){d=new JSONObject();try{data.put("days",d);}catch(Exception e){}}return d;} JSONArray ots(){JSONArray a=data.optJSONArray("overtime");if(a==null){a=new JSONArray();try{data.put("overtime",a);}catch(Exception e){}}return a;}
    String key(int d){return String.format(Locale.US,"%04d-%02d-%02d",year,month+1,d);} double hours(String a,String b){try{String[]x=a.split(":"),y=b.split(":");int m1=Integer.parseInt(x[0])*60+Integer.parseInt(x[1]),m2=Integer.parseInt(y[0])*60+Integer.parseInt(y[1]);if(m2<m1)m2+=1440;return (m2-m1)/60.0;}catch(Exception e){return 0;}}
    void renderSummary(){summary.removeAllViews();int worked=0,nights=0,oncd=0;double reg=0,vac=0,oth=0;Iterator<String>it=days().keys();while(it.hasNext()){String k=it.next();if(!k.startsWith(String.format(Locale.US,"%04d-%02d",year,month+1)))continue;JSONObject d=days().optJSONObject(k);String c=d.optString("shift","NONE");if(Arrays.asList("M","P","N","G","CUSTOM").contains(c)){worked++;reg+=hours(d.optString("start"),d.optString("end"));}if(c.equals("N"))nights++;if(c.equals("F"))vac+=VAC_HOURS;if(d.optBoolean("on_call"))oncd++;}for(int i=0;i<ots().length();i++){JSONObject o=ots().optJSONObject(i);if(o!=null&&o.optString("date").startsWith(String.format(Locale.US,"%04d-%02d",year,month+1)))oth+=o.optDouble("hours");}String[] labs={tr("worked"),tr("hours"),tr("vac"),tr("nights"),tr("onc"),tr("oth")};String[] vals={""+worked,String.format(locale(),"%.2f",reg),String.format(locale(),"%.2f",vac),""+nights,""+oncd,String.format(locale(),"%.2f",oth)};for(int i=0;i<labs.length;i++){LinearLayout c=card();c.addView(tv(labs[i],10));TextView v=tv(vals[i],17);v.setTypeface(Typeface.DEFAULT_BOLD);c.addView(v);summary.addView(c,new LinearLayout.LayoutParams(0,-2,1));}}
    void renderCalendar(){calendar.removeAllViews();String[] wd={"L","M","M","G","V","S","D"};for(String w:wd){TextView t=tv(w,11);t.setTextColor(muted);t.setGravity(Gravity.CENTER);calendar.addView(t,new GridLayout.LayoutParams(GridLayout.spec(GridLayout.UNDEFINED,1,1f),GridLayout.spec(GridLayout.UNDEFINED,1,1f)));}Calendar c=Calendar.getInstance();c.set(year,month,1);int first=(c.get(Calendar.DAY_OF_WEEK)+5)%7;int dim=c.getActualMaximum(Calendar.DAY_OF_MONTH);for(int i=0;i<first;i++){TextView blank=tv("",12);calendar.addView(blank,cellParams());}for(int d=1;d<=dim;d++){JSONObject e=days().optJSONObject(key(d));String s=""+d;if(e!=null){String code=e.optString("shift","NONE");if(!code.equals("NONE"))s+="\n"+code;if(e.optBoolean("on_call"))s+="\nRC";double ex=dayOT(d);if(ex>0)s+="\n+"+String.format(Locale.US,"%.1fh",ex);}TextView cell=tv(s,12);cell.setGravity(Gravity.TOP|Gravity.LEFT);cell.setMinHeight(dp(70));cell.setPadding(dp(7),dp(7),dp(4),dp(4));cell.setBackgroundResource(com.nexorialabpro.shiftplanner.R.drawable.day_bg);cell.setSelected(d==selectedDay);final int fd=d;cell.setOnClickListener(v->{selectedDay=fd;renderCalendar();loadSelected();renderOT();});calendar.addView(cell,cellParams());}}
    GridLayout.LayoutParams cellParams(){GridLayout.LayoutParams p=new GridLayout.LayoutParams(GridLayout.spec(GridLayout.UNDEFINED,1,1f),GridLayout.spec(GridLayout.UNDEFINED,1,1f));p.width=0;p.setMargins(dp(2),dp(2),dp(2),dp(2));return p;}
    void loadSelected(){if(selectedDay<1){startEd.setText("");endEd.setText("");noteEd.setText("");onCheck.setChecked(false);onStartEd.setText("");onEndEd.setText("");return;}JSONObject d=days().optJSONObject(key(selectedDay));if(d==null)d=new JSONObject();String code=d.optString("shift","NONE");int ix=Math.max(0,Arrays.asList(shiftCodes).indexOf(code));shiftSp.setSelection(ix);startEd.setText(d.optString("start"));endEd.setText(d.optString("end"));noteEd.setText(d.optString("note"));onCheck.setChecked(d.optBoolean("on_call"));onStartEd.setText(d.optString("on_call_start"));onEndEd.setText(d.optString("on_call_end"));}
    void applyDay(){if(selectedDay<1){toast("Select a day");return;}try{JSONObject d=new JSONObject();d.put("day",selectedDay);d.put("shift",shiftCodes[shiftSp.getSelectedItemPosition()]);d.put("start",startEd.getText().toString().trim());d.put("end",endEd.getText().toString().trim());d.put("hours",shiftCodes[shiftSp.getSelectedItemPosition()].equals("F")?VAC_HOURS:hours(d.optString("start"),d.optString("end")));d.put("note",noteEd.getText().toString());d.put("on_call",onCheck.isChecked());d.put("on_call_start",onStartEd.getText().toString());d.put("on_call_end",onEndEd.getText().toString());days().put(key(selectedDay),d);save();render();}catch(Exception e){toast(e.getMessage());}}
    void clearDay(){if(selectedDay<1)return;days().remove(key(selectedDay));JSONArray old=ots(),n=new JSONArray();for(int i=0;i<old.length();i++){JSONObject o=old.optJSONObject(i);if(o!=null&&!o.optString("date").equals(key(selectedDay)))n.put(o);}try{data.put("overtime",n);}catch(Exception e){}save();render();}
    double dayOT(int d){double h=0;for(int i=0;i<ots().length();i++){JSONObject o=ots().optJSONObject(i);if(o!=null&&o.optString("date").equals(key(d)))h+=o.optDouble("hours");}return h;}
    void addOT(){if(selectedDay<1){toast("Select a day");return;}try{double h;String man=otHoursEd.getText().toString().trim();h=man.isEmpty()?hours(otStartEd.getText().toString().trim(),otEndEd.getText().toString().trim()):Double.parseDouble(man.replace(',','.'));if(h<=0){toast("Hours = 0");return;}JSONObject o=new JSONObject();o.put("id",UUID.randomUUID().toString());o.put("date",key(selectedDay));o.put("day",selectedDay);o.put("type",otCodes[otTypeSp.getSelectedItemPosition()]);o.put("start",otStartEd.getText().toString());o.put("end",otEndEd.getText().toString());o.put("hours",h);o.put("note",otNoteEd.getText().toString());ots().put(o);otStartEd.setText("");otEndEd.setText("");otHoursEd.setText("");otNoteEd.setText("");save();render();}catch(Exception e){toast("Invalid hours");}}
    void renderOT(){if(otList==null)return;StringBuilder b=new StringBuilder();for(int i=0;i<ots().length();i++){JSONObject o=ots().optJSONObject(i);if(o!=null&&o.optString("date").equals(selectedDay<1?"":key(selectedDay)))b.append("• ").append(o.optString("type")).append("  ").append(o.optString("start")).append("–").append(o.optString("end")).append("  ").append(String.format(locale(),"%.2f h",o.optDouble("hours"))).append(o.optString("note").isEmpty()?"":" · "+o.optString("note")).append("\n");}otList.setText(b.length()==0?"—":b.toString());}
    void load(){Calendar n=Calendar.getInstance();year=n.get(Calendar.YEAR);month=n.get(Calendar.MONTH);try{String s=getPreferences(MODE_PRIVATE).getString("project","");if(!s.isEmpty()){data=new JSONObject(s);year=data.optInt("year",year);month=data.optInt("month",month+1)-1;lang=data.optString("language","it");}else{data.put("app_version","1.6-android");data.put("language",lang);data.put("year",year);data.put("month",month+1);data.put("days",new JSONObject());data.put("overtime",new JSONArray());}}catch(Exception e){data=new JSONObject();}}
    void save(){try{data.put("app_version","1.6-android");data.put("language",lang);data.put("name",nameEd==null?data.optString("name"):nameEd.getText().toString());data.put("department",deptEd==null?data.optString("department"):deptEd.getText().toString());data.put("year",year);data.put("month",month+1);getPreferences(MODE_PRIVATE).edit().putString("project",data.toString()).apply();}catch(Exception e){}}
    void openProject(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_OPEN);} void createDoc(boolean csv){save();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(csv?"text/csv":"application/json");i.putExtra(Intent.EXTRA_TITLE,"Nexoria_ShiftPlanner_"+year+"_"+String.format(Locale.US,"%02d",month+1)+(csv?".csv":".nsp"));startActivityForResult(i,csv?REQ_SAVE_CSV:REQ_SAVE_NSP);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();try{if(r==REQ_OPEN){String s=readAll(u);JSONObject x=new JSONObject(s);data=x;year=x.optInt("year",year);month=Math.max(0,x.optInt("month",month+1)-1);lang=x.optString("language",lang);save();recreate();}else if(r==REQ_SAVE_NSP)write(u,data.toString(2));else if(r==REQ_SAVE_CSV)write(u,csv());}catch(Exception e){toast(e.getMessage());}}
    String readAll(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toString("UTF-8");}void write(Uri u,String s)throws Exception{OutputStream o=getContentResolver().openOutputStream(u);o.write(s.getBytes(StandardCharsets.UTF_8));o.close();toast("OK");}
    String csv(){StringBuilder b=new StringBuilder("DAY;DATE;SHIFT;START;END;REGULAR HOURS;ON CALL;ON CALL START;ON CALL END;OVERTIME HOURS;NOTE\r\n");Calendar c=Calendar.getInstance();c.set(year,month,1);int dim=c.getActualMaximum(Calendar.DAY_OF_MONTH);for(int d=1;d<=dim;d++){JSONObject e=days().optJSONObject(key(d));if(e==null)e=new JSONObject();String code=e.optString("shift","NONE");double rh=code.equals("F")?VAC_HOURS:hours(e.optString("start"),e.optString("end"));b.append(d).append(';').append(key(d)).append(';').append(code).append(';').append(e.optString("start")).append(';').append(e.optString("end")).append(';').append(String.format(Locale.US,"%.2f",rh)).append(';').append(e.optBoolean("on_call")?"YES":"").append(';').append(e.optString("on_call_start")).append(';').append(e.optString("on_call_end")).append(';').append(String.format(Locale.US,"%.2f",dayOT(d))).append(';').append(e.optString("note").replace(';',',')).append("\r\n");}return b.toString();}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override protected void onPause(){save();super.onPause();}
}
